# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: 'pnpm-filter'
description: 'Github Action for PNPM monorepo to determine changed packages according to GIT changes.'
branding:
  icon: 'filter'
  color: 'green'
inputs:
  PAT:
    description: "Repository personal access token (PAT) to authenticate checkout action"
    required: true
outputs:
  changedPackages:
    description: "Changed packages"
    value: ${{ steps.pnpm-filter.outputs.changedPackages }}
runs:
  using: "composite"
  steps:
  - 
    uses: pnpm/action-setup@v2
    with:
      version: 8
  - 
    uses: actions/checkout@v3
    with:
      fetch-depth: 0
      token: ${{ inputs.PAT }}
  - 
    id: pnpm-filter
    shell: bash
    run: |
      changedPaths=$(pnpm --filter ...[${{ github.event.pull_request.base.sha }}] exec pwd)
      if [[ $changedPaths =~ ^No.* ]]; then changedPackages=""; else 
        changedPackages=$( sed 's|.*/||' <<< $changedPaths )
      fi
      printf 'Detected changed project: %s\n' $changedPackages
      echo changedPackages=$changedPackages >> "$GITHUB_OUTPUT"
