name: 'pnpm-filtering'
description: 'Check app source changed using pnpm filter'
inputs:
  appName:
    description: 'foldername of the pnpm project that must be checked'
    required: true
outputs:
  changed:
    description: "Bool: Source code changed"
    value: ${{ steps.check-changed.outputs.changed }}
runs:
  using: "composite"
  steps:
  - uses: pnpm/action-setup@v2
    with:
      version: 8
  - uses: actions/checkout@v2
  - id: check-changed
    shell: bash
    run: if [[ $(pnpm --filter ...[master] exec pwd) =~ ${{inputs.appName}}$ ]]; then echo changed=True; else echo changed=False; fi >> "$GITHUB_OUTPUT"
