name: 'pnpm-filter'
description: 'Github Action to determine if app source code has changed in a pnpm monorepo.'
branding:
  icon: 'filter'
  color: 'green'
inputs:
  appName:
    description: 'Project folder name of the pnpm project that must be checked'
    required: true
  PAT:
    description: "Repository PAT to authenticate checkout"
    required: true
outputs:
  changed:
    description: "Bool: Source code changed"
    value: ${{ steps.pnpm-filter.outputs.changed }}

runs:
  using: "composite"
  steps:
  - uses: pnpm/action-setup@v2
    with:
      version: 8
  - uses: actions/checkout@v3
    with:
      fetch-depth: 2
      token: ${{ inputs.PAT }}
  - id: pnpm-filter
    shell: bash
    run: |
      changedPaths=$(pnpm --filter ...[${{ github.event.pull_request.base.sha }}] exec pwd)
      printf 'Project Changed: %s\n' $changedPaths
      if [[ ${changedPaths} =~ ${{inputs.appName}}[\s]{0,1} ]]; then echo "Project Changed!"; else echo "Project Unchanged!"; fi
      if [[ ${changedPaths} =~ ${{inputs.appName}}[\s]{0,1} ]]; then echo changed=True; else echo changed=False; fi >> "$GITHUB_OUTPUT"
