name: 'pnpm-filter'
description: 'Github Action to determine if app source code has changed in a pnpm monorepo.'
branding:
  icon: 'filter'
  color: 'green'
inputs:
  appName:
    description: 'Project folder name of the pnpm project that must be checked'
    required: true
  PAT:
    description: "Repository PAT to authenticate checkout"
    required: true
outputs:
  changed:
    description: "Bool: Source code changed"
    value: ${{ steps.check-changed.outputs.changed }}

runs:
  using: "composite"
  steps:
  - uses: pnpm/action-setup@v2
    with:
      version: 8
  - uses: actions/checkout@v3
    with:
      fetch-depth: 2
      token: ${{ inputs.PAT }}
  - id: check-changed
    shell: bash
    run: if [[ $(pnpm --filter ...[${{ github.event.pull_request.base.sha }}] exec pwd) =~ ${{inputs.appName}}$ ]]; then echo changed=True; else echo changed=False; fi >> "$GITHUB_OUTPUT"
