name: 'pnpm-filter'
description: 'Github Action to determine if app source code has changed in a pnpm monorepo.'
branding:
  icon: 'filter'
  color: 'green'
inputs:
  PAT:
    description: "Repository PAT to authenticate checkout"
    required: true
outputs:
  changedProjects:
    description: "Changed Projects"
    value: ${{ steps.pnpm-filter.outputs.changedProjects }}
runs:
  using: "composite"
  steps:
  - uses: pnpm/action-setup@v2
    with:
      version: 8
  - uses: actions/checkout@v3
    with:
      fetch-depth: 2
      token: ${{ inputs.PAT }}
  - id: pnpm-filter
    shell: bash
    run: |
      changedPaths=$(pnpm --filter ...[${{ github.event.pull_request.base.sha }}] exec pwd)
      changedProjects=$( sed 's|.*/||' <<< $changedPaths )
      printf 'Detected changed project: %s\n' $changedProjects
      echo $changedProjects >> "$GITHUB_OUTPUT"
